export const HintOfLevel=[
    'X x 2',
    'First, 1 is subtracted, then 2 is added.',
    'Pattern is +5, +7, +9, +11',
    '3( *2 +1)→ 7( *3 +2) → 23( *4 +3)',
    'The numbers are perfectly divisible by 7.',
    'x+y=5, x-y=1, x=?',
    '8-1, 16-1, 32-1',
    'X * X = xyz => x+y+z ',
    'power 0=1',
    'count intersection point',
    '□ = 2',
    'x + y = z => yz',
    '1+5 =6, 6+6=12, 12+7=19,….',
    'use some basic mathematical operations applied to the three numbers in the corner of a triangle',
    'divide first and then multiply',
    'count all triangle',
    'Double of previous',
    'Try subtraction, multiplication, and addition to find the pattern.',
    'Tom is three years older than Mark.',
    'The sequence is decreasing, so this could involve subtraction.',
    'Divide both upper part number with lower part',
    'Squares have 4 side, Pentagons have 5 side, Triangles have 3 side and Hexagons have 6 side.',
    'first 14/7 =x , second 15x5=y and then x+y',
    'The sum of three numbers (both in columns and rows) is same.',
    'xy= ?? (((y+x)*(y-x))+4)',
    'Total is 11.',
    "let's apple is A. Then two apples are 2A and three apples are 3A",
    'Think of BODMAS rule.',
   'So, the sum of their ages three years ago would be (A - 3) + (R - 3) + (R - 3) = A + R + R - 9.',
   'The given series seems to be increasing by consecutive odd numbers: 3, 5, 7, 9, 11, ...',
   'Think about the pattern or rule governing the counting sequence',
   'Addition of two number',
   'Think of BODMAS rule.',
   'Next Relatable value',
   'The sequence is increasing, so this could involve addition.',
   'Multiplication of two number',
   'Any square or exponent of 1 is 1',
   '(x*2)+1',
   'Put last digit at first position',
   'x = (x*2)+1',
   'square of A',
   '(x*y)+3',
   '(x*2)+7',
   'Use subtraction concept',
   'Addition of two inner number',
   'square of A',
   '8',
   '-n',
   'square of A',
   'think of PEMDAS or BODMAS rule',
   'Muliply with x',
   '/2',
   'Adition of two vertical number is answer of the horizontal box',
   'Try multiplication, and addition to find the pattern',
    'Increase by 2 each time',
    'Adding 8 number each time',
    '(x*2)+y. Y increse with 2 number each time',
    'Tony is six years older than Mark.',
    '□ = 3',
    'Think about the pattern or rule governing the counting sequence'
]